package config

import (
	"os"
	"path/filepath"
	"testing"
)

func TestLoadConfig(t *testing.T) {
	path := writeConfig(t, `
queries:
  customers.find:
    params:
      - uuid
      - timestamp with time zone
      - text[]
`)

	cfg, err := Load(path)
	if err != nil {
		t.Fatal(err)
	}

	params := cfg.Params("customers.find")
	if len(params) != 3 {
		t.Fatalf("expected 3 params, got %d", len(params))
	}
	if params[1] != "timestamp with time zone" {
		t.Fatalf("expected normalized timestamp type, got %q", params[1])
	}
	if params[2] != "text[]" {
		t.Fatalf("expected array type, got %q", params[2])
	}
}

func TestLoadConfigAllowsEmptyParams(t *testing.T) {
	path := writeConfig(t, `
queries:
  customers.find:
    params: []
`)

	cfg, err := Load(path)
	if err != nil {
		t.Fatal(err)
	}

	if params := cfg.Params("customers.find"); len(params) != 0 {
		t.Fatalf("expected empty params, got %#v", params)
	}
}

func TestLoadConfigRejectsUnknownFields(t *testing.T) {
	path := writeConfig(t, `
queries:
  customers.find:
    args:
      - uuid
`)

	if _, err := Load(path); err == nil {
		t.Fatal("expected unknown field error")
	}
}

func TestLoadConfigRejectsUnsafeTypeName(t *testing.T) {
	path := writeConfig(t, `
queries:
  customers.find:
    params:
      - "uuid); drop table users; --"
`)

	if _, err := Load(path); err == nil {
		t.Fatal("expected unsafe type name error")
	}
}

func TestValidateQueryNames(t *testing.T) {
	path := writeConfig(t, `
queries:
  missing.query:
    params:
      - uuid
`)

	cfg, err := Load(path)
	if err != nil {
		t.Fatal(err)
	}

	err = cfg.ValidateQueryNames(map[string]struct{}{"customers.find": {}})
	if err == nil {
		t.Fatal("expected unknown query error")
	}
}

func TestGenerate(t *testing.T) {
	got := string(Generate([]string{"billing.list", "customers.find"}))
	want := `# Generated by pg-contract init.
# Fill params only when Postgres cannot infer $1, $2, ... types during PREPARE.
queries:
  billing.list:
    params: []
  customers.find:
    params: []
`
	if got != want {
		t.Fatalf("unexpected generated config:\n%s", got)
	}
}

func writeConfig(t *testing.T, content string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "pg-contract.yaml")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}
