package config

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"

	"go.yaml.in/yaml/v3"
)

var typeNamePattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*|\s+[A-Za-z_][A-Za-z0-9_]*)*(?:\[\])?$`)

type Config struct {
	Queries map[string]Query `yaml:"queries"`
}

type Query struct {
	Params []string `yaml:"params"`
}

func Load(path string) (*Config, error) {
	if strings.TrimSpace(path) == "" {
		return &Config{Queries: map[string]Query{}}, nil
	}

	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open config %s: %w", path, err)
	}
	defer file.Close()

	decoder := yaml.NewDecoder(file)
	decoder.KnownFields(true)

	var cfg Config
	if err := decoder.Decode(&cfg); err != nil {
		if err == io.EOF {
			return &Config{Queries: map[string]Query{}}, nil
		}
		return nil, fmt.Errorf("decode config %s: %w", path, err)
	}

	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		if err == nil {
			return nil, fmt.Errorf("decode config %s: multiple YAML documents are not supported", path)
		}
		return nil, fmt.Errorf("decode config %s: %w", path, err)
	}

	if cfg.Queries == nil {
		cfg.Queries = map[string]Query{}
	}

	if err := cfg.validate(); err != nil {
		return nil, fmt.Errorf("validate config %s: %w", path, err)
	}

	return &cfg, nil
}

func (c *Config) Params(queryName string) []string {
	if c == nil {
		return nil
	}

	query, ok := c.Queries[queryName]
	if !ok {
		return nil
	}

	params := make([]string, len(query.Params))
	copy(params, query.Params)
	return params
}

func (c *Config) ValidateQueryNames(known map[string]struct{}) error {
	if c == nil {
		return nil
	}

	var unknown []string
	for queryName := range c.Queries {
		if _, ok := known[queryName]; !ok {
			unknown = append(unknown, queryName)
		}
	}
	sort.Strings(unknown)

	if len(unknown) > 0 {
		return fmt.Errorf("config references unknown query %q", unknown[0])
	}

	return nil
}

func (c *Config) validate() error {
	for queryName, query := range c.Queries {
		if strings.TrimSpace(queryName) == "" {
			return fmt.Errorf("query name cannot be empty")
		}
		for i, param := range query.Params {
			normalized, err := normalizeTypeName(param)
			if err != nil {
				return fmt.Errorf("query %q param %d: %w", queryName, i+1, err)
			}
			query.Params[i] = normalized
		}
		c.Queries[queryName] = query
	}
	return nil
}

func normalizeTypeName(value string) (string, error) {
	normalized := strings.Join(strings.Fields(value), " ")
	if normalized == "" {
		return "", fmt.Errorf("type cannot be empty")
	}
	if !typeNamePattern.MatchString(normalized) {
		return "", fmt.Errorf("unsupported type name %q", value)
	}
	return normalized, nil
}

func Generate(queryNames []string) []byte {
	names := append([]string(nil), queryNames...)
	sort.Strings(names)

	var out bytes.Buffer
	out.WriteString("# Generated by pg-contract init.\n")
	out.WriteString("# Fill params only when Postgres cannot infer $1, $2, ... types during PREPARE.\n")
	out.WriteString("queries:\n")
	for _, name := range names {
		out.WriteString("  ")
		out.WriteString(name)
		out.WriteString(":\n")
		out.WriteString("    params: []\n")
	}
	return out.Bytes()
}
